### ISSUE TITLE
c3d feature vector of size 512

### ISSUE THREAD

**Issue by violivei** [zhegan27/SCN_for_video_captioning#1]
Hello,

I'm trying to replicate what you've done in the article by extracting c3d and resnet feature vectors and then running the SCN_decode.py. In the article it says c3d vectors should be of size 4096 since we are extracting them from layer fc7. However, I've noticed that the shape of your dataset (the c3d.mat files provided) is equal to 512. Which step am I missing?

Thanks in advance.

**Comment by pyc40** [comment]
Hi violivei,

The provided feature is from pool5 layer with global average pooling on the spatiotemporal dimensions.

**Comment by zhegan27** [comment]
Hi violivei, 

As pyc40 replied to you already, we used the feature from pool5 layer instead. In our experiments, we found this feature vector performs similarly compared with the feature from layer fc7. Let us know if any further question.

Best,
Zhe
