### ISSUE TITLE
how to extract the video features

### ISSUE THREAD

**Issue by Dawson-huang** [zhegan27/SCN_for_video_captioning#3]
How do you extract the video features from the Raw video data on the youtube dataset?
please help me, thank you very mach!

**Comment by zhegan27** [comment]
Hi,

Sorry for my late responses. Hope it still helps your research. 

The video tagging code and trained model is included in the github now. Please have a check.
For ResNet feature and C3D feature extraction, please refer to other resources. Thanks for your interest in our work.

Best,
Zhe

**Comment by Dawson-huang** [comment]
Hi,
Thank you for your previde!!
It will be helpful for my work!
