### ISSUE TITLE
How to predict semantic attributes

### ISSUE THREAD

**Issue by jinjinyuan** [zhegan27/SCN_for_video_captioning#4]
how did you predict semantic attributes?  could you release the code of predict semantic attributes?

**Comment by zzha5029** [comment]
Or could you give some detail information about how to extract tag of semantic attributes?

**Comment by zhegan27** [comment]
Hi,

Sorry for my late responses. Hope the reply below is still helpful.  

The video tagging code is included in the github now. Please have a check. Thanks for your interest in our work. Let me know if any further question. 

Best,
Zhe
