### ISSUE TITLE
whatis the x[5] means? how to create it?

### ISSUE THREAD

**Issue by jinjinyuan** [zhegan27/SCN_for_video_captioning#5]
x = cPickle.load(open("./data/youtube2text/corpus.p", "rb"))
train, val, test = x[0], x[1], x[2]    
wordtoix, ixtoword = x[3], x[4]
W = x[5]

**Comment by zhegan27** [comment]
W = x[5], which is a 12594*300 matrix, storing the pre-trained word embedding extracted from the word2vec. This requires downloading the binary file (i.e. GoogleNews-vectors-negative300.bin file) from https://code.google.com/p/word2vec/. 

After doing this, you can run the newly added obtain_pretrained_word2vec.py file to get the pre-trained word embedding. 

This matrix can be used for initializing the word embedding matrix: 
params['Wemb'] = W.astype(config.floatX)

However, you can also choose to initialize your word embedding matrix randomly:
params['Wemb'] = uniform_weight(n_words,n_x)

Typically initializing the word embedding matrix with word2vec will provide slightly better performance than initializing this matrix randomly. 

Hope this helps your research!
