### ISSUE TITLE
How to extract captioning features_

### ISSUE THREAD

**Issue by kamal4493** [zhegan27/SCN_for_video_captioning#6]
Hi

Thank you for providing the code for the paper . I want to apply this technique to a new data set . So I need to know how captioning features were extracted.
Any help is appreciated

Regards
Kamal

**Comment by zhegan27** [comment]
Hi Kamal,

The video tagging code is included in the github now. Please have a check. 
For ResNet feature and C3D feature extraction, please refer to other resources. Thanks for your interest in our work. 

Best, 
Zhe
