### ISSUE TITLE
How could I feed in a video for captioning?

### ISSUE THREAD

**Issue by chikiuso** [zhegan27/SCN_for_video_captioning#7]
Hi, it walkthrough all steps, it is a great project! 

How could I feed in a video for captioning? Thanks.

**Comment by zhegan27** [comment]
Hi, thanks for your interest in our work. When doing the project, the C3D features are extracted under the linux system, while the ResNet features are extracted under the windows system, so it is not easy to for me to combine them together for a demo purpose as you request. 

However, I have updated my image captioning repo (https://github.com/zhegan27/Semantic_Compositional_Nets) and now it contains a demo code with a dropbox link that is able to detect tags and generates captions for an image from scratch. You can have a check if you are interested. 
 
I may create a demo code that could feed in a video for captioning end-to-end later when I find time. 

Thanks for your patience!
